version: '3.3'

services:
  db: #container mysql
    image: mysql:5.7 # FROM mysql:5.7
    volumes:
      - mysql:/var/libr/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress: #container mysql
    depends_on:
      - db
    image: wordpress:latest # FROM wordpress
    ports:
      - "8000:80"
    restart: always
    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}