version: '3.3'

services:
  db: #container mysql
    image: mysql:5.7 # FROM mysql:5.7
    volumes:
      - mysql:/var/libr/mysql
    restart: always
    env_file:
      - ./config/db.env
    networks:
      - backend

  wordpress: #container mysql
    depends_on:
      - db
    image: wordpress:latest # FROM wordpress
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/wp.env
    networks:
      - backend

volumes:
  mysql: {}
networks:
  backend: